/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as DossierIdRouteImport } from './routes/dossier.$id'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const DossierIdRoute = DossierIdRouteImport.update({
  id: '/dossier/$id',
  path: '/dossier/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/demo': typeof DemoRoute
  '/entities': typeof EntitiesRoute
  '/evidence': typeof EvidenceRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/dossier/$id': typeof DossierIdRoute
  '/reports/$id': typeof ReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/demo': typeof DemoRoute
  '/entities': typeof EntitiesRoute
  '/evidence': typeof EvidenceRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/dossier/$id': typeof DossierIdRoute
  '/reports/$id': typeof ReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/demo': typeof DemoRoute
  '/entities': typeof EntitiesRoute
  '/evidence': typeof EvidenceRoute
  '/overview': typeof OverviewRoute
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/dossier/$id': typeof DossierIdRoute
  '/reports/$id': typeof ReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/demo'
    | '/entities'
    | '/evidence'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/dossier/$id'
    | '/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/demo'
    | '/entities'
    | '/evidence'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/dossier/$id'
    | '/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/demo'
    | '/entities'
    | '/evidence'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/dossier/$id'
    | '/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  DemoRoute: typeof DemoRoute
  EntitiesRoute: typeof EntitiesRoute
  EvidenceRoute: typeof EvidenceRoute
  OverviewRoute: typeof OverviewRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  DossierIdRoute: typeof DossierIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/dossier/$id': {
      id: '/dossier/$id'
      path: '/dossier/$id'
      fullPath: '/dossier/$id'
      preLoaderRoute: typeof DossierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  DemoRoute: DemoRoute,
  EntitiesRoute: EntitiesRoute,
  EvidenceRoute: EvidenceRoute,
  OverviewRoute: OverviewRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  DossierIdRoute: DossierIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
